# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [4]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10

In [8]:
# Create a 3x3 null matrix
# null_matrix = np.zeros((3, 3))
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [9]:
# nbytes attribute gives the total number of bytes consumed by the elements of the array
print(null_vector.nbytes)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [10]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\mehru\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where t

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [12]:
vector_1 = np.zeros(10)
vector_1[4] = 1
print(vector_1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [14]:
# numpy.arange(start, stop, step, dtype=None)
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [21]:
vector_2 = np.array([1, 2, 3, 4, 5])
print(vector_2[::-1])

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [23]:
array_1 = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array_1)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [25]:
print(np.eye(3,3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [27]:
print(np.random.rand(3,3,3))

[[[0.74623142 0.24506215 0.06225031]
  [0.62495715 0.50061856 0.34867205]
  [0.3090055  0.48932627 0.83949234]]

 [[0.91456623 0.41030951 0.78645676]
  [0.08046346 0.01894974 0.25696878]
  [0.53544343 0.1689684  0.7812881 ]]

 [[0.53859982 0.07154864 0.80028826]
  [0.48179342 0.91254239 0.51030522]
  [0.49108076 0.10075905 0.13108586]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [29]:
array_3 = np.random.rand(10,10)
print(np.max(array_3))
print(np.min(array_3))

0.9925842568182971
0.02210631813740571


#### 14. Create a random vector of size 30 and find the mean value

In [32]:
vector_3 = np.random.rand(30)
# Find the mean value
# mean_value = np.mean(vector)
print(np.mean(vector_3))

0.45694337419899606


#### 15. Create a 2d array with 1 on the border and 0 inside

In [37]:
size = 4
border_array = np.zeros((size,size), dtype = int)
border_array[0,:] = 1
border_array[-1, :] = 1
border_array[:,0] = 1
border_array[:,-1] = 1
size = 4
print(border_array)
# zeros(shape, dtype=float, order='C', *, like=None)
# Return a new array of given shape and type, filled with zeros.

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [41]:
# np.random.randint(low, high=None, size=None, dtype=int)
random_array = np.random.randint(2,20,size=(4,5))
random_array[0,:]=0
random_array[-1,:]=0
random_array[:,0]=0
random_array[:,-1]=0
print(random_array)


[[ 0  0  0  0  0]
 [ 0 14  5  2  0]
 [ 0 18 19  4  0]
 [ 0  0  0  0  0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# False
# False
# nan
# True
# False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [46]:
# Define the size of the matrix
size = 5

# Create an empty matrix of zeros
matrix = np.zeros((size, size), dtype=int)

# Set values just below the diagonal
for i in range(1, size):
    matrix[i, i-1] = i  # i-1 is the column index just below the diagonal

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [47]:
# Define the size of the matrix
size = 8

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((size, size), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[0::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# index = 99 // since 100th element is indexed at 99
# x=index//(size of Y×size of Z)
# y=(index//size of Z)%size of Y
# z=index%size of Z
# z = 99%8
# y = (99//8)%7
# x = 99//(7 X 8)