In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
python.exe -m pip install --upgrade pip

SyntaxError: invalid syntax (842801469.py, line 1)

In [3]:
pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/d4/55/90db48d85f7689ec6f81c0db0622d704306c5284850383c090e6c7195a5c/pip-24.2-py3-none-any.whl.metadata
  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
type(arr)


numpy.ndarray

In [6]:
#n-dimentional array
# can find no.of dimentions using ndim
arr.ndim

2

In [10]:
#no. of rows, columns
arr.shape

(2, 3)

In [14]:

# Creating an array from a list with type float
a = np.array([[1, 2, 4], [5, 7, 8]], dtype='float')
print('Array created using passed list:\n', a)


Array created using passed list:
 [[1. 2. 4.]
 [5. 7. 8.]]


In [15]:
#  Creating array from tuple
b = np.array((1,3,2))
print('Array created using passed tuple :\n', b)

Array created using passed tuple :
 [1 3 2]


In [17]:
# Creating 3X4 array with all zeroes
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Constant value, complex dtype array
d = np.full((3,3), 6,dtype='complex')
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [19]:
# Random values array
e = np.random.random((2,2))
print(e)

[[0.84131212 0.34266054]
 [0.5700494  0.7971223 ]]


In [20]:
# Sequence of integers with steps of 5
print(np.arange(0,30,5))

[ 0  5 10 15 20 25]


In [ ]:
# to know more about a function, function_name+'?' + shift+enter
# eg. np.arange?

In [25]:
# 10 values between 0 and 5, sequentially
print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [26]:
# arr.reshape(2,2,3) -> 3X4 to 2X2X3
# arr.flatten() -> will flatten array to a single object


In [28]:
cd

C:\Users\mehru


In [29]:
!git init

Initialized empty Git repository in C:/Users/mehru/.git/


In [30]:
!git config --global user.name "g-faheem"

In [31]:
!git config --global user.email "faheem.h.shaikh@gmail.com"

In [ ]:
!git remote add origin https://github.com/g-faheem/AI-Mafia--Machine-Learning.git
